/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

#import <Foundation/Foundation.h>

#import "TProtocol.h"
#import "TApplicationException.h"
#import "TProtocolUtil.h"
#import "TProcessor.h"
#import "TObjective-C.h"

#import "Recipe.h"

@protocol makcipeAPIRecipeAPI <NSObject>
- (NSString *) getAll: (NSString *) table;  // throws TException
- (makcipeAPIRecipe *) make_All_Recipe_list;  // throws TException
- (NSMutableArray *) make_Recc_Recipe_list;  // throws TException
- (NSMutableArray *) make_Subc_Recipe_list;  // throws TException
- (NSMutableArray *) make_norm_Recipe_list: (NSString *) r_id;  // throws TException
@end

@interface makcipeAPIRecipeAPIClient : NSObject <makcipeAPIRecipeAPI> {
  id <TProtocol> inProtocol;
  id <TProtocol> outProtocol;
}
- (id) initWithProtocol: (id <TProtocol>) protocol;
- (id) initWithInProtocol: (id <TProtocol>) inProtocol outProtocol: (id <TProtocol>) outProtocol;
@end

@interface makcipeAPIRecipeAPIProcessor : NSObject <TProcessor> {
  id <makcipeAPIRecipeAPI> mService;
  NSDictionary * mMethodMap;
}
- (id) initWithRecipeAPI: (id <makcipeAPIRecipeAPI>) service;
- (id<makcipeAPIRecipeAPI>) service;
@end

@interface makcipeAPIRecipeAPIConstants : NSObject {
}
@end
