//
// Autogenerated by Thrift Compiler (0.9.0)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//
var Thrift = require('thrift').Thrift;
var Recipe_ttypes = require('./Recipe_types')


var ttypes = require('./RecipeAPI_types');
//HELPER FUNCTIONS AND STRUCTURES

RecipeAPI_RecipeSearch_args = function(args) {
  this.token = null;
  this.name = null;
  if (args) {
    if (args.token !== undefined) {
      this.token = args.token;
    }
    if (args.name !== undefined) {
      this.name = args.name;
    }
  }
};
RecipeAPI_RecipeSearch_args.prototype = {};
RecipeAPI_RecipeSearch_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.STRING) {
        this.token = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 2:
      if (ftype == Thrift.Type.STRING) {
        this.name = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

RecipeAPI_RecipeSearch_args.prototype.write = function(output) {
  output.writeStructBegin('RecipeAPI_RecipeSearch_args');
  if (this.token !== null && this.token !== undefined) {
    output.writeFieldBegin('token', Thrift.Type.STRING, 1);
    output.writeString(this.token);
    output.writeFieldEnd();
  }
  if (this.name !== null && this.name !== undefined) {
    output.writeFieldBegin('name', Thrift.Type.STRING, 2);
    output.writeString(this.name);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

RecipeAPI_RecipeSearch_result = function(args) {
};
RecipeAPI_RecipeSearch_result.prototype = {};
RecipeAPI_RecipeSearch_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    input.skip(ftype);
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

RecipeAPI_RecipeSearch_result.prototype.write = function(output) {
  output.writeStructBegin('RecipeAPI_RecipeSearch_result');
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

RecipeAPI_REcipeAllSearch_args = function(args) {
};
RecipeAPI_REcipeAllSearch_args.prototype = {};
RecipeAPI_REcipeAllSearch_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    input.skip(ftype);
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

RecipeAPI_REcipeAllSearch_args.prototype.write = function(output) {
  output.writeStructBegin('RecipeAPI_REcipeAllSearch_args');
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

RecipeAPI_REcipeAllSearch_result = function(args) {
};
RecipeAPI_REcipeAllSearch_result.prototype = {};
RecipeAPI_REcipeAllSearch_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    input.skip(ftype);
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

RecipeAPI_REcipeAllSearch_result.prototype.write = function(output) {
  output.writeStructBegin('RecipeAPI_REcipeAllSearch_result');
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

RecipeAPIClient = exports.Client = function(output, pClass) {
    this.output = output;
    this.pClass = pClass;
    this.seqid = 0;
    this._reqs = {};
};
RecipeAPIClient.prototype = {};
RecipeAPIClient.prototype.RecipeSearch = function(token, name, callback) {
  this.seqid += 1;
  this._reqs[this.seqid] = callback;
  this.send_RecipeSearch(token, name);
};

RecipeAPIClient.prototype.send_RecipeSearch = function(token, name) {
  var output = new this.pClass(this.output);
  output.writeMessageBegin('RecipeSearch', Thrift.MessageType.CALL, this.seqid);
  var args = new RecipeAPI_RecipeSearch_args();
  args.token = token;
  args.name = name;
  args.write(output);
  output.writeMessageEnd();
  return this.output.flush();
};

RecipeAPIClient.prototype.recv_RecipeSearch = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new RecipeAPI_RecipeSearch_result();
  result.read(input);
  input.readMessageEnd();

  callback(null)
};
RecipeAPIClient.prototype.REcipeAllSearch = function(callback) {
  this.seqid += 1;
  this._reqs[this.seqid] = callback;
  this.send_REcipeAllSearch();
};

RecipeAPIClient.prototype.send_REcipeAllSearch = function() {
  var output = new this.pClass(this.output);
  output.writeMessageBegin('REcipeAllSearch', Thrift.MessageType.CALL, this.seqid);
  var args = new RecipeAPI_REcipeAllSearch_args();
  args.write(output);
  output.writeMessageEnd();
  return this.output.flush();
};

RecipeAPIClient.prototype.recv_REcipeAllSearch = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new RecipeAPI_REcipeAllSearch_result();
  result.read(input);
  input.readMessageEnd();

  callback(null)
};
RecipeAPIProcessor = exports.Processor = function(handler) {
  this._handler = handler
}
RecipeAPIProcessor.prototype.process = function(input, output) {
  var r = input.readMessageBegin();
  if (this['process_' + r.fname]) {
    return this['process_' + r.fname].call(this, r.rseqid, input, output);
  } else {
    input.skip(Thrift.Type.STRUCT);
    input.readMessageEnd();
    var x = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN_METHOD, 'Unknown function ' + r.fname);
    output.writeMessageBegin(r.fname, Thrift.MessageType.Exception, r.rseqid);
    x.write(output);
    output.writeMessageEnd();
    output.flush();
  }
}

RecipeAPIProcessor.prototype.process_RecipeSearch = function(seqid, input, output) {
  var args = new RecipeAPI_RecipeSearch_args();
  args.read(input);
  input.readMessageEnd();
  this._handler.RecipeSearch(args.token, args.name, function (err, result) {
    var result = new RecipeAPI_RecipeSearch_result((err != null ? err : {success: result}));
    output.writeMessageBegin("RecipeSearch", Thrift.MessageType.REPLY, seqid);
    result.write(output);
    output.writeMessageEnd();
    output.flush();
  })
}

RecipeAPIProcessor.prototype.process_REcipeAllSearch = function(seqid, input, output) {
  var args = new RecipeAPI_REcipeAllSearch_args();
  args.read(input);
  input.readMessageEnd();
  this._handler.REcipeAllSearch(function (err, result) {
    var result = new RecipeAPI_REcipeAllSearch_result((err != null ? err : {success: result}));
    output.writeMessageBegin("REcipeAllSearch", Thrift.MessageType.REPLY, seqid);
    result.write(output);
    output.writeMessageEnd();
    output.flush();
  })
}

