/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.foodRecipe.core.thrift.model.user;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum AUTH_METHOD implements org.apache.thrift.TEnum {
  FACEBOOK(1),
  KAKAO(16),
  EMAIL(256);

  private final int value;

  private AUTH_METHOD(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static AUTH_METHOD findByValue(int value) { 
    switch (value) {
      case 1:
        return FACEBOOK;
      case 16:
        return KAKAO;
      case 256:
        return EMAIL;
      default:
        return null;
    }
  }
}
