/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.foodRecipe.core.thrift.model.user;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum SIGNUP_STATUS implements org.apache.thrift.TEnum {
  SIGNUP(1),
  CERTIFICATED(2),
  WITHDREW(3);

  private final int value;

  private SIGNUP_STATUS(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static SIGNUP_STATUS findByValue(int value) { 
    switch (value) {
      case 1:
        return SIGNUP;
      case 2:
        return CERTIFICATED;
      case 3:
        return WITHDREW;
      default:
        return null;
    }
  }
}
