/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.foodRecipe.core.thrift.model.recipe;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum RECIPETYPE implements org.apache.thrift.TEnum {
  NONE(1),
  RECOMM(2),
  SUBSC(3);

  private final int value;

  private RECIPETYPE(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static RECIPETYPE findByValue(int value) { 
    switch (value) {
      case 1:
        return NONE;
      case 2:
        return RECOMM;
      case 3:
        return SUBSC;
      default:
        return null;
    }
  }
}
